#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z "${KOPIA_UI_PASSWORD}" ]]; then
    echo "ERROR: You must set a password for the Web UI"
    exit 1
fi

SUBJECT="/C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
if [[ -f /config/keys/kopia.key && -f /config/keys/kopia.crt ]]; then
    echo "using keys found in /config/keys"
else
    echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
    mkdir -p /config/keys
    rm -f \
        /config/keys/kopia.key \
        /config/keys/kopia.crt || true
    openssl req -new -x509 -days 3650 -nodes -out /config/keys/kopia.crt -keyout /config/keys/kopia.key -subj "${SUBJECT}" -addext "subjectAltName = DNS:localhost"
fi
