#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ${KOPIA_HTTPS,,} == "true" ]]; then
    if curl -skL "https://localhost:51515/api/v1/control/status" | jq -r '.connected' > /dev/null 2>&1; then
        exit 0
    else
        exit 1
    fi
else
    if curl -skL "https://localhost:51515/api/v1/control/status" | jq -r '.connected' > /dev/null 2>&1; then
        exit 0
    else
        exit 1
    fi
fi
