name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-and-release.yml@v8.0.4
    with:
      repo_owner: "thespad"
      app_name: "kopia-server"
      release_type: "github"
      release_url: "https://api.github.com/repos/kopia/kopia"
      dockerhub_user: "thespad"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
      dockerhub_password: ${{ secrets.docker_password }}
