name: Check for base image updates

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-baseimage-update.yml@v9.0.2
    with:
      repo_owner: "thespad"
      baseimage: "alpine"
      basebranch: "3.22"
      app_name: "kopia-server"
      branch_name: "main"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
