name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-image.yml@v7
    with:
      repo_owner: "thespad"
      app_name: "kopia-server"
      release_type: "github"
      release_url: "https://api.github.com/repos/kopia/kopia"      
      dockerhub_user: "thespad"
      target-arch: "64"
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
